name: Deployment

on:
  push:
    branches:
      main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up NodeJS 
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14'

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.2

      - name: Build App
        run: |
          npm i
          npm run build

      - name: Package App
        run: |
          npm ci --only=prod
          npm i -g @ffflorian/jszip-cli mkdirp
          npm run build:zip
        
      - name: Initialise terraform
        run: |
          cd deployment
          terraform init
        env:
          ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}

      - name: Apply terraform
        run: |
          cd deployment
          terraform apply -auto-approve
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
